<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="lin33005536" failures="1" tests="5" name="Personal loan" time="0.142" errors="0" timestamp="2025-01-17T00:49:28 IST">
  <testcase classname="com.learn.section16.day1" name="Demo" time="0.033">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.learn.section16.day1.Demo(day1.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="com.learn.section16.day2" name="ploan" time="0.002"/>
  <testcase classname="com.learn.section16.day4" name="LoginAPIHomeLoan" time="0.003"/>
  <testcase classname="com.learn.section16.day4" name="MobileLoginHomeLoan" time="0.004"/>
  <testcase classname="com.learn.section16.day4" name="WebloginHomeLoan" time="0.003"/>
  <testcase classname="com.learn.section16.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
